# Gateway configurations for Venusia Gopher server
#
# This file configures process-based gateways that can be accessed
# through the Gopher server.

[[gateway]]
selector = "/gateway/cowsay"
search = true
wildcard = false
command = "cowsay"
arguments = ["$search"]
menu = true

[[gateway]]
selector = "/gateway/ollama/*"
search = true
wildcard = true
command = "ollama"
arguments = ["run", "$search", "$wildcard"]
menu = true
preamble = ["7New query\t/gateway/ollama/llama3:latest/\tlocalhost\t7071"]
postamble = ["7New query\t/gateway/ollama/llama3:latest/\tlocalhost\t7071"]

[[gateway]]
selector = "/gateway/weather"
search = true
wildcard = false
command = "curl"
arguments = ["https://wttr.in/$search?format=v2"]
menu = true

[[gateway]]
selector = "/gateway/figlet/*"
search = true
wildcard = true
command = "figlet"
arguments = ["$search", "$wildcard"]
menu = true

[[gateway]]
selector = "/gateway/echo-process"
search = false
wildcard = true
command = "echo"
arguments = ["$wildcard"]
menu = false