# Gateway configurations for Venusia Gopher server
#
# This file configures process-based gateways that can be accessed
# through the Gopher server.

[gateways.cowsay]
selector = "/gateway/cowsay"
search = true
wildcard = false
command = "cowsay"
arguments = ["$search"]
menu = true

[gateways.ollama]
selector = "/gateway/ollama/*"
search = true
wildcard = true
command = "ollama"
arguments = ["run", "$search", "$wildcard"]
menu = true

[gateways.weather]
selector = "/gateway/weather"
search = true
wildcard = false
command = "curl"
arguments = ["https://wttr.in/$search?format=v2"]
menu = true

[gateways.figlet]
selector = "/gateway/figlet/*"
search = true
wildcard = true
command = "figlet"
arguments = ["$search", "$wildcard"]
menu = true

[gateways.echo-process]
selector = "/gateway/echo-process"
search = false
wildcard = true
command = "echo"
arguments = ["$wildcard"]
menu = false