name:                Venusia
version:             0.1.0.0
github:              "someodd/Venusia"
license:             BSD-3-Clause
author:              "someodd"
maintainer:          "someodd@pm.me"
copyright:           "2025 someodd"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Internet Gopher Protocol server framework, including tools for menus
category:            Network

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/someodd/Venusia#readme>

dependencies:
- base

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  default-extensions:
  - OverloadedStrings
  - DeriveGeneric
  - DeriveAnyClass
  - OverloadedRecordDot
  - DuplicateRecordFields
  default-language: GHC2021
  dependencies:
  - bytestring
  - containers
  - directory
  - filepath
  - time
  - network
  - text
  - unordered-containers
  - process
  - tomland
  - hashable
  - unix
  - utf8-string

executables:
  Venusia-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Venusia
    - bytestring
    - text
    default-extensions:
    - OverloadedStrings
    - DeriveGeneric
    - DeriveAnyClass
    - OverloadedRecordDot
    - DuplicateRecordFields

tests:
  Venusia-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Venusia
