# Gateway configurations for Venusia Gopher server
#
# This file configures process-based gateways that can be accessed
# through the Gopher server.

[[gateway]]
selector = "/gateway/cowsay"
search = true
wildcard = false
command = "cowsay"
arguments = ["$search"]
menu = true

[[gateway]]
selector = "/gateway/ollama/*"
search = true
wildcard = true
command = "ollama"
arguments = ["run", "$search", "$wildcard"]
menu = true
preamble = ["7New query\t/gateway/ollama/llama3:latest/\tlocalhost\t7071"]
postamble = ["7New query\t/gateway/ollama/llama3:latest/\tlocalhost\t7071"]

[[gateway]]
selector = "/gateway/weather"
search = true
wildcard = false
command = "curl"
arguments = ["https://wttr.in/$search?format=v2"]
menu = true

[[gateway]]
selector = "/gateway/figlet/*"
search = true
wildcard = true
command = "figlet"
arguments = ["$search", "$wildcard"]
menu = true

[[gateway]]
selector = "/gateway/echo-process"
search = false
wildcard = true
command = "echo"
arguments = ["$wildcard"]
menu = false

# [[search]] defines a route that uses the built-in search handler.
[[search]]
selector = "/search"
path = "/var/gopher/searchable"

[[search]]
selector = "/search-docs"
path = "./"

# [[files]] defines a route that uses the built-in file server.
# The selector MUST end with '/*' to capture the path.
[[files]]
selector = "/files/*"
path = "./"

[[files]]
selector = "/images/*"
path = "/var/gopher/images"